DATA_DESCRIPTION = [
    {
        "start": 0,
        "end": 9,
        "length": 9,
        "field_name": "DUNS",
        "field_description": "DUN'S NUMBER",
    },
    {
        "start": 10,
        "end": 39,
        "length": 30,
        "field_name": "DCOMP",
        "field_description": "BUSINESS NAME",
    },
    {
        "start": 40,
        "end": 69,
        "length": 30,
        "field_name": "DTRADE",
        "field_description": "SECONDARY NAME",
    },
    {
        "start": 70,
        "end": 94,
        "length": 25,
        "field_name": "DSTREET",
        "field_description": "STREET ADDRESS",
    },
    {
        "start": 95,
        "end": 114,
        "length": 20,
        "field_name": "DCITY",
        "field_description": "CITY",
    },
    {
        "start": 115,
        "end": 116,
        "length": 2,
        "field_name": "DSTATEAB",
        "field_description": "STATE ABBREVIATION",
    },
    {
        "start": 117,
        "end": 121,
        "length": 5,
        "field_name": "DZIP5",
        "field_description": "ZIP CODE FOR STREET ADDRESS",
    },
    {
        "start": 122,
        "end": 125,
        "length": 4,
        "field_name": "DZIP4EXT",
        "field_description": "ZIP + 4 EXTENTION FOR STREET ADDRESS",
    },
    {
        "start": 126,
        "end": 150,
        "length": 25,
        "field_name": "DMAILADD",
        "field_description": "MAILING ADDRESS",
    },
    {
        "start": 151,
        "end": 170,
        "length": 20,
        "field_name": "DMAILCIT",
        "field_description": "MAILING CITY NAME",
    },
    {
        "start": 171,
        "end": 172,
        "length": 2,
        "field_name": "DMAILSTA",
        "field_description": "MAILING STATE ABBREVIATION",
    },
    {
        "start": 173,
        "end": 177,
        "length": 5,
        "field_name": "DMAILZIP",
        "field_description": "MAILING ZIP CODE",
    },
    {
        "start": 178,
        "end": 181,
        "length": 4,
        "field_name": "DMAILZP4",
        "field_description": "MAILING ZIP + 4 EXTENTION",
    },
    {
        "start": 182,
        "end": 185,
        "length": 4,
        "field_name": "DCARRRTC",
        "field_description": "CARRIER ROUTE CODE (BLANK IF NOT REQUESTED)",
    },
    {
        "start": 186,
        "end": 187,
        "length": 2,
        "field_name": "FILLER0",
        "field_description": "NOT USED - MAY BE ALL BLANKS",
    },
    {
        "start": 188,
        "end": 190,
        "length": 3,
        "field_name": "DNATLCOD",
        "field_description": "NATIONAL CODES",
    },
    {
        "start": 191,
        "end": 192,
        "length": 2,
        "field_name": "DSTATECO",
        "field_description": "DUN AND BRADSTREET STATE CODE",
    },
    {
        "start": 193,
        "end": 195,
        "length": 3,
        "field_name": "DCOUNTYC",
        "field_description": "DUN AND BRADSTREET COUNTY CODE",
    },
    {
        "start": 196,
        "end": 199,
        "length": 4,
        "field_name": "DCITYCOD",
        "field_description": "DUN AND BRADSTREET CITY CODE",
    },
    {
        "start": 200,
        "end": 202,
        "length": 3,
        "field_name": "DSMSACOD",
        "field_description": "DUN AND BRADSTREET SMSA CODE",
    },
    {
        "start": 203,
        "end": 212,
        "length": 10,
        "field_name": "DTELEPHO",
        "field_description": "TELEPHONE NUMBER. THERE ARE NO HYPHENS",
    },
    {
        "start": 213,
        "end": 242,
        "length": 30,
        "field_name": "DCEONAME",
        "field_description": "CEO NAME AND TITLE",
    },
    {
        "start": 243,
        "end": 272,
        "length": 30,
        "field_name": "DCEOTITT",
        "field_description": "DDM TITLE",
    },
    {
        "start": 273,
        "end": 287,
        "length": 15,
        "field_name": "DSALESVO",
        "field_description": "SALES VOLUME",
    },
    {
        "start": 288,
        "end": 288,
        "length": 1,
        "field_name": "DSLSVOLC",
        "field_description": "CODE FOR ESTIMATE OR RANGE",
    },
    {
        "start": 289,
        "end": 297,
        "length": 9,
        "field_name": "DEMTLTOT",
        "field_description": "EMPLOYEES TOTAL",
    },
    {
        "start": 298,
        "end": 298,
        "length": 1,
        "field_name": "DEMTOTC",
        "field_description": "CODE FOR ESTIMATE OR RANGE",
    },
    {
        "start": 299,
        "end": 307,
        "length": 9,
        "field_name": "DEMTLHER",
        "field_description": "EMPLOYEES HERE",
    },
    {
        "start": 308,
        "end": 308,
        "length": 1,
        "field_name": "DEMPHRCD",
        "field_description": "CODE FOR ESTIMATE OR RANGE",
    },
    {
        "start": 309,
        "end": 312,
        "length": 4,
        "field_name": "DYRSTART",
        "field_description": "YEAR STARTED",
    },
    {
        "start": 313,
        "end": 313,
        "length": 1,
        "field_name": "DSTATUSI",
        "field_description": "STATUS INDICATOR",
    },
    {
        "start": 314,
        "end": 314,
        "length": 1,
        "field_name": "DSUBSIDI",
        "field_description": "SUBSIDIARY INDICATOR",
    },
    {
        "start": 315,
        "end": 315,
        "length": 1,
        "field_name": "DMANUFIN",
        "field_description": "MANUFACTURING INDICATOR",
    },
    {
        "start": 316,
        "end": 324,
        "length": 9,
        "field_name": "DULTDUN",
        "field_description": "ULTIMATE DUNS",
    },
    {
        "start": 325,
        "end": 333,
        "length": 9,
        "field_name": "DHDQDUN",
        "field_description": "HEADQUARTERS DUNS",
    },
    {
        "start": 334,
        "end": 342,
        "length": 9,
        "field_name": "DPARDUN",
        "field_description": "PARENT DUNS",
    },
    {
        "start": 343,
        "end": 362,
        "length": 20,
        "field_name": "DPRHQCT",
        "field_description": "PARENT OR HEADQUARTERS CITY",
    },
    {
        "start": 363,
        "end": 364,
        "length": 2,
        "field_name": "DPRHQST",
        "field_description": "PARENT OR HEADQUARTERS STATE ABBREVIATION",
    },
    {
        "start": 365,
        "end": 372,
        "length": 9,
        "field_name": "FILLER1",
        "field_description": "NOT USED - MAY BE ALL BLANKS or ZEROS",
    },
    {
        "start": 373,
        "end": 382,
        "length": 9,
        "field_name": "FILLER2",
        "field_description": "NOT USED - MAY BE ALL BLANKS or ZEROS",
    },
    {
        "start": 383,
        "end": 384,
        "length": 2,
        "field_name": "DHIER",
        "field_description": "HIERARCHY CODE - DOES NOT CONFORM TO WB",
    },
    {
        "start": 385,
        "end": 393,
        "length": 9,
        "field_name": "DDIAS",
        "field_description": "DIAS CODE - DOES NOT CONFORM TO WB",
    },
    {
        "start": 394,
        "end": 394,
        "length": 1,
        "field_name": "DPOPLCD",
        "field_description": "POPULATION CODE(BLANK IF NOT REQUESTED)",
    },
    {
        "start": 395,
        "end": 395,
        "length": 1,
        "field_name": "DTRANCD",
        "field_description": "TRANSACTION CODES.",
    },
    {
        "start": 396,
        "end": 401,
        "length": 6,
        "field_name": "DRPTDAT",
        "field_description": "D&B REPORT DATE",
    },
    {
        "start": 402,
        "end": 420,
        "length": 19,
        "field_name": "FILLER3",
        "field_description": "USER AREA - WILL BE BLANK",
    },
    {
        "start": 421,
        "end": 421,
        "length": 1,
        "field_name": "DRCRDCL",
        "field_description": "RECORD CLASS TYPE (BLANK IF NOT REQUESTED)",
    },
    {
        "start": 422,
        "end": 440,
        "length": 19,
        "field_name": "DLINEBU",
        "field_description": "LINE OF BUSINESS. THIS CONTAINS A 19",
    },
    {
        "start": 441,
        "end": 444,
        "length": 4,
        "field_name": "DPRIMSI",
        "field_description": "GOVERNMENT DEFINED SIC CODE",
    },
    {
        "start": 445,
        "end": 448,
        "length": 4,
        "field_name": "DSICEXT1",
        "field_description": "DUN AND BRADSTREET 2 + 2 EXTENTION",
    },
    {
        "start": 449,
        "end": 452,
        "length": 4,
        "field_name": "DSICEXT2",
        "field_description": "DUN AND BRADSTREET 2 + 2 EXTENTION",
    },
    {
        "start": 453,
        "end": 456,
        "length": 4,
        "field_name": "DSICEXT3",
        "field_description": "DUN AND BRADSTREET 2 + 2 EXTENTION",
    },
    {
        "start": 457,
        "end": 460,
        "length": 4,
        "field_name": "DSICEXT4",
        "field_description": "DUN AND BRADSTREET 2 + 2 EXTENTION",
    },
    {
        "start": 461,
        "end": 480,
        "length": 20,
        "field_name": "DSIC2",
        "field_description": "SIC 2 SAME FORMAT AS PRIMARY SIC",
    },
    {
        "start": 481,
        "end": 500,
        "length": 20,
        "field_name": "DSIC3",
        "field_description": "SIC 3 SAME FORMAT AS PRIMARY SIC",
    },
    {
        "start": 501,
        "end": 520,
        "length": 20,
        "field_name": "DSIC4",
        "field_description": "SIC 4 SAME FORMAT AS PRIMARY SIC",
    },
    {
        "start": 521,
        "end": 540,
        "length": 20,
        "field_name": "DSIC5",
        "field_description": "SIC 5 SAME FORMAT AS PRIMARY SIC",
    },
    {
        "start": 541,
        "end": 560,
        "length": 20,
        "field_name": "DSIC6",
        "field_description": "SIC 6 SAME FORMAT AS PRIMARY SIC",
    },
]
